name: ci
on :
  pull_request:
    branches: ['*']
jobs:
  unit-tests :
    runs-on : ubuntu-latest
    strategy :
      matrix :
        node-version: [22.x]
    steps:
      - name: Copy Repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: npm ci

      - name : Generate Prisma
        run: npm run generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build
        run: npm run build

      # - name : check DB URL
      #   run: echo $DATABASE_URL
      #   env:
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run unit tests
        run : npm test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Run Integration tests
        run: cd apps/server && npm run test:e2e
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
